spring:
  application:
    name: truck-tracking
  profiles:
#    active: prod
    include: test



#  jackson:
#    property-naming-strategy:
#        SNAKE_CASE
#  api-docs:
#    enabled: true
#  swagger-ui:
#    url: swagger.yaml
