openapi: 3.0.3
info:
  version: 1.0.0
  title: Truck tracking
  description: Truck tracking jest to moja implementacja założeń zadania rekrutacyjnego dla firmy fireTMS.
              Cała aplikacja jest zabezpieczona metodą BasicAuth z istniejącym użytkownikiem/hasłem **'fire/tms'**
  contact:
    name: Janusz Kuźnik
    email: janusz.kuznik89@gmail.com
    url: http://www.github.com/jkuznik
servers:
  - url: 'http://localhost:8080'
    description: 'Server URL in Development environment'
  - url: 'http://localhost:8081'
    description: 'Server URL in Production environment'
externalDocs:
  description: Treść zadania
  url: http://localhost:8080/zadanie.html
tags:
  - name: trailer
    description: Metody CRUD przewidziane według założeń zadania
    externalDocs:
      description: Treść zadania
      url: http://localhost:8080/zadanie.html
  - name: truck
    description: Metody CRUD przewidziane według założeń zadania
    externalDocs:
      description: Treść zadania
      url: http://localhost:8080/zadanie.html

paths:

  /trailer:
    get:
      tags:
        - trailer
      summary: Zwraca listę wszystkich naczep
      security:
        - basicAuth: [ ]
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia

    post:
      tags:
        - trailer
      summary: Dodawanie naczepy
      security:
        - basicAuth: [ ]
      responses:
        201:
          description: Dodano naczepę
        401:
          description: Brak uwierzytelnienia

  /trailer/{uuid}:

    get:
      tags:
        - trailer
      summary: Zwraca naczepę według UUID
      security:
        - basicAuth: [ ]
      parameters:
        - name: uuid
          in: path
          description: UUID identyfikujący naczepę o id 1 w bazie danych
          required: true
          example: 542602cf-97d5-4548-8831-55f21d35fcf4
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia
        404:
          description: Naczepa o podanym UUID nie isteniej

    delete:
      tags:
        - trailer
      summary: Usuwanie naczepy według UUID
      security:
        - basicAuth: [ ]
      parameters:
        - name: uuid
          in: path
          description: UUID identyfikujący naczepę o id 1 w bazie danych
          required: true
          example: 542602cf-97d5-4548-8831-55f21d35fcf4
      responses:
        204:
          description: Usunięto naczepę
        401:
          description: Brak uwierzytelnienia
        404:
          description: Naczepa o podanym UUID nie istnieje

  /trailer/history:
    get:
      tags:
        - trailer
      summary: Zwraca historię przypisań naczep według podanych filtrów; okres czasu w którym naczepa była użytkowana
      security:
        - basicAuth: [ ]
      parameters:
        - name: startDate
          in: query
          required: false
          schema:
            type: timestamp
            description: tutaj mozna uzupelnic wypelnianie parametrów
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia

  /trailer/search:
    get:
      tags:
        - trailer
      summary: Zwraca listę aktualnego stanu naczep według podanych filtrów; czy aktualnie jest w użytku, czy naczepa jest oflagowana jako 'corssHitch', okres czasu w którym naczepa była użytkowana
      security:
        - basicAuth: [ ]
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia

  /trailer/{uuid}/cross-hitch:
    patch:
      tags:
        - trailer
      summary: Endpoint odpowiedzialny za operacje 'cross hitch'
      security:
        - basicAuth: [ ]
      responses:
        200:
          description: Komunikat informacyjny o wyniku operacji
        401:
          description: Brak uwierzytelnienia

  /truck:
    get:
      tags:
        - truck
      summary: Zwraca listę wszystkich pojazdów
      security:
        - basicAuth: [ ]
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia

    post:
      tags:
        - truck
      summary: Dodawanie pojazdu
      security:
        - basicAuth: [ ]
      responses:
        201:
          description: Dodano pojazd
        401:
          description: Brak uwierzytelnienia

  /truck/{uuid}:
    get:
      tags:
        - truck
      summary: Zwraca pojazd według UUID
      security:
        - basicAuth: [ ]
      parameters:
        - name: uuid
          in: path
          description: UUID identyfikujący pojazd o id 1 w bazie danych
          required: true
          example: 52333a07-520e-465f-a6c2-5891080637e5
      responses:
        200:
          description: Operacja udana
        401:
          description: Brak uwierzytelnienia
        404:
          description: Pojazd o podanym UUID nie istnieje

    patch:
      tags:
        - truck
      summary: Endpoint służący do zarządzania naczepami dla danego ciągnika oraz planowanym okresem przypisania naczepy, pozostałe parametry ciągnika z natury powinny być finalnymi
      security:
        - basicAuth: [ ]
      parameters:
        - name: uuid
          in: path
          description: UUID identyfikujący ciągnik o id 1 w bazie danych
          example: 52333a07-520e-465f-a6c2-5891080637e5
      responses:
        200:
          description: Operacja udana
        400:
          description: Błąd żądania - nie prawidłowe dane
        401:
          description: Brak uwierzytelnienia
        404:
          description: Pojazd o podanym UUID nie istnieje
        500:
          description: Błąd serwera

    delete:
      tags:
        - truck
      summary: Usuwanie pojazdu według UUID
      security:
        - basicAuth: [ ]
      parameters:
        - name: uuid
          in: path
          description: UUID identyfikujący pojazd o id 1 w bazie danych
          required: true
          example: 52333a07-520e-465f-a6c2-5891080637e5
      responses:
        204:
          description: Usunięto pojazd
        401:
          description: Brak uwierzytelnienia
        404:
          description: Pojazd o podanym UUId nie istnieje

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic



